<html>
<head>


<? 
echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/layout.css');
 echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/mainSlider.css');
 echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/productsGallery.css');

 ?>

<?php
if($this->JQuery()->isEnabled())
{
$this->JQuery()->setLocalPath($this->baseUrl()."/js/JQuery/js/jquery-1.7.1.min.js")
	->setUiLocalPath($this->baseUrl()."/js/JQuery/js/jquery-ui-1.8.18.custom.min.js")
	->addStyleSheet($this->baseUrl()."/js/JQuery/css/ui-lightness/jquery-ui-1.8.18.custom.css");
echo $this->JQuery();
}
?>

<script type="text/javascript" src="<?php echo $this->baseUrl()."/js/mainSlider.js";?>"></script>

<script type="text/javascript" src="<?php echo $this->baseUrl()."/js/productsGallery.js";?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl()."/js/jquery.easing.1.3.js";?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl()."/js/jquery.timers-1.2.js";?>"></script>

</head>
<body>
<div id="mainDiv">


<div id="mHeader">
<a href="<?php echo $this->baseUrl()."/index"?>">
<img id="logo" src='<?php echo $this->baseUrl()."/images/logo.png";?>' alt="LOGO" style={position:absolute;top:-19px;} />
</a>

<table cellspacing="0">
<tr>
<td>
<a href="<?php echo $this->baseUrl()."/index/story"?>">

<img class="circles" id="storyCircle" src='<?php echo $this->baseUrl()."/images/StoryCircle.png";?>' alt="Story" />
</a>

</td>

<td>
<a href='<?php echo $this->baseUrl()."/index/products"?> '>
<img class="circles" id="productsCircle" src='<?php echo $this->baseUrl()."/images/productsCircle.png";?>' alt="Products" />
</a>
</td>

<td>

<a href="<?php echo $this->baseUrl()."/index/location"?>">
<img class="circles" id="locationCircle" src='<?php echo $this->baseUrl()."/images/locationCircle.png";?>' alt="Location" />
</a>
</td>

<td>
<a href="<?php echo $this->baseUrl()."/index/contact-us"?>">
<img class="circles" id="contactCircle" src='<?php echo $this->baseUrl()."/images/contactCircle.png";?>' alt="Contact Us" />
</a>
</td>


</tr>

<tr>
<td style={position:absolute;left:8%;}>
<a href="<?php echo $this->baseUrl()."/index/story"?>">
 Story
</a>
 </td>

<td>
<a href="<?php echo $this->baseUrl()."/index/products"?>">
 Products 
</a>
</td>
<td>
<a href="<?php echo $this->baseUrl()."/index/location"?>">
Location
</a>
</td>

<td > 
<a href="<?php echo $this->baseUrl()."/index/contact-us"?>">
Contact Us </td>
</a>
</tr>
</table>
</div>

<div id="mBody">
<?php echo $this->layout()->content; ?>
</div>


<div id="mfooter">

</div>

</div>
</br>



</body>
</html>
